exports.regexpList = [
  /(\W|^)bars?(\W|$)/i,
  /(\W|^)restaurant(\W|$)/i,
  /(\W|^)buy(\W|$)/i,
  /(\W|^)bring food(\W|$)/i,
  /(\W|^)brewery(\W|$)/i,
  /(\W|^)cost(\W|$)/i,
  /(\W|^)food bank(\W|$)/i,
  /(\W|^)purchase(\W|$)/i,
  /(\W|^)early birds?(\W|$)/i,
  /(\W|^)memberships?(\W|$)/i,
  /(\W|^)pricy(\W|$)/i,
  /(\W|^)nonrefundable(\W|$)/i,
  /(\W|^)happy hour(\W|$)/i,
  /(\W|^)tickets?(\W|$)/i,
  /(\W|^)fees?(\W|$)/i,
  /(\W|^)sales?(\W|$)/i,
  /(\W|^)farmers? markets?(\W|$)/i,
  /(\W|^)b\.?y\.?o\.?b?(\W|$)/i,
];

exports.venueTerms = [
  /(\W|^)bars?(\W|$)/i,
  /(\W|^)bakery?(\W|$)/i,
  /(\W|^)restaurants?(\W|$)/i,
  /(\W|^)brewery(\W|$)/i,
  /(\W|^)food banks?(\W|$)/i,
  /(\W|^)cafes?(\W|$)/i,
  /(\W|^)hospitals?(\W|$)/i,
  /(\W|^)shelters?(\W|$)/i,
  /(\W|^)taqueria(\W|$)/i,
  /(\W|^)clubs?(\W|$)/i,
  /(\W|^)lounges?(\W|$)/i,
  /(\W|^)apartments?(\W|$)/i,
  /(\W|^)homes?(\W|$)/i,
  /(\W|^)diners?(\W|$)/i,
  /(\W|^)food banks?(\W|$)/i,
  /(\W|^)private(\W|$)/i,
  /(\W|^)residence(\W|$)/i,
  /(\W|^)kitchens?(\W|$)/i,
  /(\W|^)coffees?(\W|$)/i,
  /(\W|^)winery?(\W|$)/i,
  /(\W|^)festivals?(\W|$)/i,
]