exports.regexpList = [
  /burgers?/i,
  /pizzas?/i,
  /hot dogs?/i,
  /beers?/i,
  /sushis?/i,
  /drinks/i,
  /foods?/i,
  /snacks?/i,
  /burgers?/i,
  /sangrias?/i,
  /potluck/i,
  /wines?/i,
  /coffees?/i,
  /donuts?/i,
  /pastr(y|ies)/i,
  /refreshments?/i,
  /cookies?/i,
  /grub/i,
  /beverages?/i,
  /cupcakes?/i,
  /desserts?/i,
  /tacos?/i,
  /cocktails?/i,
  /munchies?/i,
  /pancakes?/i,
  /cheeses?/i,
  // /^treats?/i,
  // /^pies?/i,
];